#docker-compose up
#docker-compose exec web python manage.py createsuperuser
#see https://github.com/Ehco1996/django-sspanel/wiki/%E9%9D%A2%E6%9D%BF%E9%83%A8%E7%BD%B2
version: '3'

services:
  db:
    image: daocloud.io/mysql:5.6
    container_name : sspanel-db    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpass
      MYSQL_DATABASE: sspanel
    volumes:
      - ./configs/mysqld/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - mysql-data:/var/lib/mysql
    networks: 
      - sspanel_network
  web:
    container_name : sspanel-web
    build:
      context: .
      dockerfile: Dockerfile
    image: sspanel
    environment:
      MYSQL_PASSWORD: yourpass
      MYSQL_HOST: db
    volumes:
      - .:/src/django-sspanel
      - static/:/src/django-sspanel/static      
    ports:
      - 8080:8080
    depends_on:
      - db
    networks: 
      - sspanel_network
  nginx:
    image: daocloud.io/nginx
    restart: always    
    container_name : sspanel-nginx
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d
      - static/:/src/django-sspanel/static
    ports:
      - 80:80
    depends_on:
      - web
    networks: 
      - sspanel_network
networks:
  sspanel_network:
volumes:
  static:
  mysql-data: